const Cards = [

    "Fear thou not; for I am with thee: be not dismayed; for I am thy God. – Isaiah 41:10",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him. – Nahum 1:7",
  "The eternal God is thy refuge, and underneath are the everlasting arms. – Deuteronomy 33:27",
  "He shall cover thee with his feathers, and under his wings shalt thou trust. – Psalm 91:4",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord shall bless thee, and keep thee. – Numbers 6:24",
  "Cast thy burden upon the Lord, and he shall sustain thee. – Psalm 55:22",
  "The Lord is nigh unto all them that call upon him. – Psalm 145:18",
  "The righteous cry, and the Lord heareth, and delivereth them out of all their troubles. – Psalm 34:17",
  "The Lord is good unto them that wait for him. – Lamentations 3:25",
  "The Lord will give strength unto his people; the Lord will bless his people with peace. – Psalm 29:11",
  "The angel of the Lord encampeth round about them that fear him. – Psalm 34:7",
  "He healeth the broken in heart, and bindeth up their wounds. – Psalm 147:3",
  "The steps of a good man are ordered by the Lord. – Psalm 37:23",
  "The Lord knoweth the days of the upright. – Psalm 37:18",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "He giveth power to the faint; and to them that have no might he increaseth strength. – Isaiah 40:29",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "Surely goodness and mercy shall follow me all the days of my life. – Psalm 23:6",
  "The Lord will perfect that which concerneth me. – Psalm 138:8",
  "The Lord will strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord will be a refuge for the oppressed. – Psalm 9:9",
  "The Lord shall preserve thy going out and thy coming in. – Psalm 121:8",
  "The Lord is righteous in all his ways. – Psalm 145:17",
  "The Lord taketh pleasure in them that fear him. – Psalm 147:11",
  "The Lord will not forsake his people. – Psalm 94:14",
  "The Lord shall fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord thy God in the midst of thee is mighty. – Zephaniah 3:17",
  "The Lord is a buckler to all those that trust in him. – Psalm 18:30",
  "The Lord is good to all: and his tender mercies are over all his works. – Psalm 145:9",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord is gracious, and full of compassion. – Psalm 145:8",
  "The Lord hath done great things for us; whereof we are glad. – Psalm 126:3",
  "The Lord is my strength and my shield. – Psalm 28:7",
  "The Lord will make perfect that which concerneth me. – Psalm 138:8",
  "The Lord hath been mindful of us: he will bless us. – Psalm 115:12",
  "The Lord is near unto them that are of a broken heart. – Psalm 34:18",
  "The Lord will give grace and glory. – Psalm 84:11",
  "The Lord shall increase you more and more. – Psalm 115:14",
  "Trust in the Lord with all thine heart; and lean not unto thine own understanding. – Proverbs 3:5",
  "In all thy ways acknowledge him, and he shall direct thy paths. – Proverbs 3:6",
  "The name of the Lord is a strong tower: the righteous runneth into it, and is safe. – Proverbs 18:10",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord is my rock, and my fortress, and my deliverer. – Psalm 18:2",
  "The Lord is good unto them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord is my strength and my shield; my heart trusted in him, and I am helped. – Psalm 28:7",
  "The Lord will give strength unto his people; the Lord will bless his people with peace. – Psalm 29:11",
  "The Lord is nigh unto all them that call upon him. – Psalm 145:18",
  "The Lord is righteous in all his ways, and holy in all his works. – Psalm 145:17",
  "The Lord hath appeared of old unto me, saying, Yea, I have loved thee with an everlasting love. – Jeremiah 31:3",
  "The Lord is my helper, and I will not fear what man shall do unto me. – Hebrews 13:6",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord will be a refuge for the oppressed. – Psalm 9:9",
  "The Lord shall guide thee continually, and satisfy thy soul in drought. – Isaiah 58:11",
  "The Lord hath done great things for us; whereof we are glad. – Psalm 126:3",
  "The Lord will perfect that which concerneth me. – Psalm 138:8",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord is gracious, and full of compassion. – Psalm 145:8",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "The Lord will strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord will hear when I call unto him. – Psalm 4:3",
  "The Lord is good, and his mercy endureth for ever. – Psalm 100:5",
  "The Lord will not cast off his people. – Psalm 94:14",
  "The Lord is merciful and gracious, slow to anger, and plenteous in mercy. – Psalm 103:8",
  "The Lord shall preserve thy going out and thy coming in. – Psalm 121:8",
  "The Lord will give grace and glory. – Psalm 84:11",
  "The Lord is faithful, who shall stablish you, and keep you from evil. – 2 Thessalonians 3:3",
  "The Lord shall fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord is a sun and shield: the Lord will give grace and glory. – Psalm 84:11",
  "The Lord will not forsake his inheritance. – Psalm 94:14",
  "The Lord is my portion, saith my soul; therefore will I hope in him. – Lamentations 3:24",
  "The Lord is nigh unto them that are of a broken heart. – Psalm 34:18",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord will give strength unto his people. – Psalm 29:11",
  "The Lord shall preserve thy soul. – Psalm 121:7",
  "The Lord is faithful, who shall stablish you. – 2 Thessalonians 3:3",
  "The Lord will do that which is good in his sight. – 1 Samuel 3:18",
  "The Lord is my helper; I will not fear what man shall do unto me. – Hebrews 13:6",
  "When thou passest through the waters, I will be with thee; and through the rivers, they shall not overflow thee. – Isaiah 43:2",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "The Lord is my light and my salvation; whom shall I fear? the Lord is the strength of my life; of whom shall I be afraid? – Psalm 27:1",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord is my strength and my shield; my heart trusted in him, and I am helped. – Psalm 28:7",
  "The Lord is nigh unto all them that call upon him, to all that call upon him in truth. – Psalm 145:18",
  "The Lord will give strength unto his people; the Lord will bless his people with peace. – Psalm 29:11",
  "The angel of the Lord encampeth round about them that fear him, and delivereth them. – Psalm 34:7",
  "The Lord redeemeth the soul of his servants: and none of them that trust in him shall be desolate. – Psalm 34:22",
  "The Lord shall guide thee continually, and satisfy thy soul in drought. – Isaiah 58:11",
  "The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him. – Nahum 1:7",
  "The Lord is my portion, saith my soul; therefore will I hope in him. – Lamentations 3:24",
  "The Lord will perfect that which concerneth me: thy mercy, O Lord, endureth for ever. – Psalm 138:8",
  "The Lord is righteous in all his ways, and holy in all his works. – Psalm 145:17",
  "The Lord is gracious, and full of compassion; slow to anger, and of great mercy. – Psalm 145:8",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord is my strength and my song, and is become my salvation. – Exodus 15:2",
  "The Lord will fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord is my rock, and my fortress, and my deliverer. – Psalm 18:2",
  "The Lord shall preserve thy going out and thy coming in from this time forth, and even for evermore. – Psalm 121:8",
  "The Lord is my helper, and I will not fear what man shall do unto me. – Hebrews 13:6",
  "The Lord will bless thee out of Zion, and thou shalt see the good of Jerusalem all the days of thy life. – Psalm 128:5",
  "The Lord is good unto them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord will give grace and glory: no good thing will he withhold from them that walk uprightly. – Psalm 84:11",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is nigh unto them that are of a broken heart; and saveth such as be of a contrite spirit. – Psalm 34:18",
  "The Lord shall strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord will not forsake his people for his great name's sake. – 1 Samuel 12:22",
  "The Lord is faithful, who shall stablish you, and keep you from evil. – 2 Thessalonians 3:3",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord hath done great things for us; whereof we are glad. – Psalm 126:3",
  "The Lord will give grace and glory: no good thing will he withhold. – Psalm 84:11",
  "The Lord is my strength and my song; he also is become my salvation. – Isaiah 12:2",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord will keep thee from all evil; he will keep thy soul. – Psalm 121:7",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord will preserve thee from all evil. – Psalm 121:7",
  "The Lord is my helper. – Hebrews 13:6",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is my strength and my song, and is become my salvation. – Exodus 15:2",
  "The Lord shall guide thee continually, and satisfy thy soul in drought. – Isaiah 58:11",
  "The Lord is good, a strong hold in the day of trouble; and he knoweth them that trust in him. – Nahum 1:7",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "The Lord is my helper, and I will not fear what man shall do unto me. – Hebrews 13:6",
  "The Lord will give strength unto his people; the Lord will bless his people with peace. – Psalm 29:11",
  "The Lord is good unto them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord will be a refuge for the oppressed. – Psalm 9:9",
  "The Lord is gracious, and full of compassion. – Psalm 145:8",
  "The Lord will perfect that which concerneth me. – Psalm 138:8",
  "The Lord will give grace and glory. – Psalm 84:11",
  "The Lord shall preserve thy going out and thy coming in. – Psalm 121:8",
  "The Lord is good to all: and his tender mercies are over all his works. – Psalm 145:9",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord will not forsake his people. – Psalm 94:14",
  "The Lord is my rock, and my fortress, and my deliverer. – Psalm 18:2",
  "The Lord is righteous in all his ways. – Psalm 145:17",
  "The Lord shall give strength unto his people. – Psalm 29:11",
  "The Lord is nigh unto all them that call upon him. – Psalm 145:18",
  "The Lord shall fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord will not cast off his people. – Psalm 94:14",
  "The Lord is good, and his mercy endureth for ever. – Psalm 100:5",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is faithful, who shall stablish you, and keep you from evil. – 2 Thessalonians 3:3",
  "The Lord is my strength and my shield; my heart trusted in him. – Psalm 28:7",
  "The Lord is near unto them that are of a broken heart. – Psalm 34:18",
  "The Lord will hear when I call unto him. – Psalm 4:3",
  "The Lord will bless thee and keep thee. – Numbers 6:24",
  "The Lord will keep thee from all evil. – Psalm 121:7",
  "The Lord will guide thee continually. – Isaiah 58:11",
  "The Lord is good to those that wait for him. – Lamentations 3:25",
  "The Lord will preserve thee from all evil. – Psalm 121:7",
  "The Lord is my helper. – Hebrews 13:6",
  "The Lord will strengthen thee. – Psalm 27:14",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord is gracious and full of compassion. – Psalm 145:8",
  "The Lord will be with thee whithersoever thou goest. – Joshua 1:9",
  "The Lord will give thee rest. – Exodus 33:14",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord shall renew their strength. – Isaiah 40:31",
  "The Lord is faithful that promised. – Hebrews 10:23",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "The Lord will give grace and glory: no good thing will he withhold from them that walk uprightly. – Psalm 84:11",
  "The Lord is my strength and my shield; my heart trusted in him. – Psalm 28:7",
  "The Lord is good unto them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord is my rock, and my fortress, and my deliverer. – Psalm 18:2",
  "The Lord will preserve thee from all evil. – Psalm 121:7",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord is righteous in all his ways, and holy in all his works. – Psalm 145:17",
  "The Lord is nigh unto all them that call upon him. – Psalm 145:18",
  "The Lord shall strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord will not forsake his people. – Psalm 94:14",
  "The Lord is my strength and song. – Exodus 15:2",
  "The Lord will bless thee and keep thee. – Numbers 6:24",
  "The Lord will give strength unto his people. – Psalm 29:11",
  "The Lord will be a refuge for the oppressed. – Psalm 9:9",
  "The Lord is my helper. – Hebrews 13:6",
  "The Lord is gracious and full of compassion. – Psalm 145:8",
  "The Lord shall preserve thy going out and thy coming in. – Psalm 121:8",
  "The Lord will perfect that which concerneth me. – Psalm 138:8",
  "The Lord is good, and his mercy endureth for ever. – Psalm 100:5",
  "The Lord shall give that which is good. – Psalm 85:12",
  "The Lord will give strength to his people. – Psalm 29:11",
  "The Lord is my defence. – Psalm 94:22",
  "The Lord shall be thy confidence. – Proverbs 3:26",
  "The Lord is my portion, saith my soul. – Lamentations 3:24",
  "The Lord will guide thee with his counsel. – Psalm 73:24",
  "The Lord is near unto them that are of a broken heart. – Psalm 34:18",
  "The Lord will be thy confidence. – Proverbs 3:26",
  "The Lord is faithful, who shall stablish you. – 2 Thessalonians 3:3",
  "The Lord will not leave thee, nor forsake thee. – Deuteronomy 31:6",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord shall fight for you. – Exodus 14:14",
  "The Lord will hear when I call unto him. – Psalm 4:3",
  "The Lord is good unto all. – Psalm 145:9",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord is near unto all them that call upon him. – Psalm 145:18",
  "The Lord will strengthen thee. – Psalm 27:14",
  "The Lord shall preserve thy soul. – Psalm 121:7",
  "The Lord will be with thee. – Joshua 1:9",
  "The Lord is my light. – Psalm 27:1",
  "The Lord will establish you. – 2 Thessalonians 3:3",
  "The Lord will bless thee in the land. – Deuteronomy 28:8",
  "The Lord will make thee plenteous in goods. – Deuteronomy 28:11",
  "The Lord will open unto thee his good treasure. – Deuteronomy 28:12",
  "The Lord shall bless thee in all that thou doest. – Deuteronomy 15:10",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord shall bless thee out of Zion, and thou shalt see the good of Jerusalem all the days of thy life. – Psalm 128:5",
  "The Lord is my portion, saith my soul; therefore will I hope in him. – Lamentations 3:24",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord will bless thee, and keep thee. – Numbers 6:24",
  "The Lord will preserve thy going out and thy coming in from this time forth, and even for evermore. – Psalm 121:8",
  "The Lord is good to them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord is my helper, and I will not fear what man shall do unto me. – Hebrews 13:6",
  "The Lord is righteous in all his ways, and holy in all his works. – Psalm 145:17",
  "The Lord will strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord is my strength and my song, and is become my salvation. – Exodus 15:2",
  "The Lord shall guide thee continually, and satisfy thy soul in drought. – Isaiah 58:11",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord shall give strength unto his people; the Lord shall bless his people with peace. – Psalm 29:11",
  "The Lord is nigh unto all them that call upon him. – Psalm 145:18",
  "The Lord will be with thee. – Joshua 1:9",
  "The Lord will not forsake his people. – Psalm 94:14",
  "The Lord will guide thee with his counsel. – Psalm 73:24",
  "The Lord is gracious, and full of compassion. – Psalm 145:8",
  "The Lord is my strength and my shield. – Psalm 28:7",
  "The Lord shall fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord will keep thee from all evil. – Psalm 121:7",
  "The Lord is good unto all: and his tender mercies are over all his works. – Psalm 145:9",
  "The Lord shall bless thee out of Zion. – Psalm 128:5",
  "The Lord is near unto all them that call upon him. – Psalm 145:18",
  "The Lord will bless thee and keep thee. – Numbers 6:24",
  "The Lord shall preserve thee from all evil. – Psalm 121:7",
  "The Lord will strengthen thee. – Psalm 27:14",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord will give grace and glory. – Psalm 84:11",
  "The Lord will bless thee with peace. – Psalm 29:11",
  "The Lord is my helper. – Hebrews 13:6",
  "The Lord will keep thee from falling. – Jude 1:24",
  "The Lord is my portion, saith my soul. – Lamentations 3:24",
  "The Lord shall renew their strength. – Isaiah 40:31",
  "The Lord will bless thee in all thy works. – Deuteronomy 15:10",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord will not leave thee, nor forsake thee. – Deuteronomy 31:6",
  "The Lord shall reign for ever and ever. – Exodus 15:18",
  "The Lord is my strength and my song, and he is become my salvation. – Exodus 15:2",
  "The Lord will not forsake his people for his great name's sake. – 1 Samuel 12:22",
  "The Lord is my rock, and my fortress, and my deliverer. – Psalm 18:2",
  "The Lord will bless the righteous; with favour wilt thou compass him as with a shield. – Psalm 5:12",
  "The Lord is my defence; and my God is the rock of my refuge. – Psalm 94:22",
  "The Lord is good unto them that wait for him, to the soul that seeketh him. – Lamentations 3:25",
  "The Lord shall preserve thee from all evil. – Psalm 121:7",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord is a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord is good, and his mercy endureth for ever. – Psalm 100:5",
  "The Lord will be a refuge for the oppressed. – Psalm 9:9",
  "The Lord is my portion, saith my soul. – Lamentations 3:24",
  "The Lord is nigh unto them that are of a broken heart. – Psalm 34:18",
  "The Lord is faithful, who shall stablish you, and keep you from evil. – 2 Thessalonians 3:3",
  "The Lord shall preserve thee from all evil: he shall preserve thy soul. – Psalm 121:7",
  "The Lord will give strength unto his people. – Psalm 29:11",
  "The Lord shall bless thee and keep thee. – Numbers 6:24",
  "The Lord is my helper, and I will not fear what man shall do unto me. – Hebrews 13:6",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The Lord is good to all: and his tender mercies are over all his works. – Psalm 145:9",
  "The Lord will strengthen him upon the bed of languishing. – Psalm 41:3",
  "The Lord shall preserve thy going out and thy coming in. – Psalm 121:8",
  "The Lord is gracious, and full of compassion. – Psalm 145:8",
  "The Lord is my strength and my shield. – Psalm 28:7",
  "The Lord shall give strength unto his people; the Lord shall bless his people with peace. – Psalm 29:11",
  "The Lord will bless thee out of Zion. – Psalm 128:5",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "The Lord will give grace and glory. – Psalm 84:11",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "The Lord will keep thee from all evil. – Psalm 121:7",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "The Lord will bless thee and keep thee. – Numbers 6:24",
  "The Lord shall preserve thy soul. – Psalm 121:7",
  "The Lord is my strength and my song. – Exodus 15:2",
  "The Lord will not forsake his people. – Psalm 94:14",
  "The Lord shall fight for you. – Exodus 14:14",
  "The Lord is near unto all them that call upon him. – Psalm 145:18",
  "The Lord will be with thee. – Joshua 1:9",
  "The Lord will give strength unto his people. – Psalm 29:11",
  "The Lord is my shepherd; I shall not want. – Psalm 23:1",
  "Fear thou not; for I am with thee. – Isaiah 41:10",
  "The Lord shall fight for you, and ye shall hold your peace. – Exodus 14:14",
  "The Lord is good, a strong hold in the day of trouble. – Nahum 1:7",
  "I will never leave thee, nor forsake thee. – Hebrews 13:5",
  "The Lord is my light and my salvation; whom shall I fear? – Psalm 27:1",
  "The joy of the Lord is your strength. – Nehemiah 8:10",
  "Commit thy way unto the Lord; trust also in him. – Psalm 37:5",
  "The Lord will perfect that which concerneth me. – Psalm 138:8",
  "Be strong and of a good courage. – Joshua 1:9",
  "The Lord shall guide thee continually. – Isaiah 58:11",
  "He healeth the broken in heart. – Psalm 147:3",
  "Cast thy burden upon the Lord, and he shall sustain thee. – Psalm 55:22",
  "The Lord is my refuge and my fortress. – Psalm 91:2",
  "My grace is sufficient for thee. – 2 Corinthians 12:9",
  "Trust in the Lord with all thine heart. – Proverbs 3:5",
  "The Lord is near unto all them that call upon him. – Psalm 145:18",
  "Wait on the Lord: be of good courage. – Psalm 27:14",
  "The Lord will bless thee and keep thee. – Numbers 6:24",
  "He shall give his angels charge over thee. – Psalm 91:11"
]
